### ISSUE TITLE
Typo in CONTRIBUTING.md

### ISSUE THREAD

**Issue by dayvancowboy13** [TheOdinProject/.github#27]
In the [Curriculum Repo section](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md#curriculum-repo): 

> Any suggestions or **changed** to specific lesson content belong there.

Should probably be "changes."

**Comment by IshaanKulkarni** [comment]
https://github.com/TheOdinProject/.github/pull/28

Raised a PR to fix this. Thanks for bringing this to the notice of fellow contributors!
