### ISSUE TITLE
Docs: Add SECURITY.md file

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/.github#6]
**Because**
* We should have a policy / way for people to contact us if there is a security issue in any of our repos.

**Notes**
See https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository for more details

**Comment by CBID2** [comment]
Is this issue still open? I would like to work on it @ChargrilledChook.

**Comment by devashishroychowdhury** [comment]
Is this issue opened I can fix it

**Comment by CBID2** [comment]
Hi @KevinMulhern! :) Can I still work on this issue? I asked [4 months ago](https://github.com/TheOdinProject/.github/issues/6#issuecomment-1569508504) but didn't get a response.

**Comment by KevinMulhern** [comment]
Thanks for the interest both, it looks like Github guides team admins through how to set one up with a template, so this is best left for us to do.
